### ISSUE TITLE
How to get method and http version?

### ISSUE THREAD

**Issue by leobuskin** [dontcare/httpparser#5]
How to get request method and http version? on_url callback return url only, right?

P.S. Perfect API, looks like a nice drop-in replacement for http-parser-based httptools from MagicStack, I was looking for picohttpparser-based solution with callbacks and your project is perfect fits my needs.

**Comment by dontcare** [comment]
```python
import httpparser

class Protocol:

    def __init__(self):
        self.parser = httpparser.Request(self)

    def on_header(self, name, value):
        pass

    def on_headers(self, headers):
        pass

    def on_uri(self, uri):
        pass

    def on_body(self, body):
        pass

    def on_complete(self):
        print(self.parser.get_method())
        print(self.parser.get_http_version())
        print(self.parser.should_keep_alive())

    def data_received(self, data):
        self.parser.parse(data)
```

**Comment by leobuskin** [comment]
Oh, thanks for such a fast support! Does `get_method` and `get_http_version` available on `on_uri` callback or `on_complete` only? Sorry for being an asshole and asking such questions via issues, I've never used wrappers like this before and to be frankly it's a bit difficult to understand how it works reading pyx/pxd. Thank you.

**Comment by dontcare** [comment]
```python
def on_uri(self, url):
    print(uri,` self.parser.get_method(), self.parser.get_http_version())
````
